name: bfnlibrary
description: BFN Library
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
#  crypted_preferences: ^0.0.2
  firebase_auth: ^0.15.3+1
  firebase_messaging: ^6.0.9
  cloud_firestore: ^0.13.0+1
  intl: ^0.16.1
  shared_preferences: ^0.5.6
  dynamic_theme: 1.0.1
#  autocomplete_textfield: ^1.7.3
#  path_provider: ^1.5.1
  flutter_dotenv: ^2.1.0
  google_fonts: ^0.3.2
  getflutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

