myconfig:
  partyA: http://192.168.86.240:10050/
  partyB: http://192.168.86.240:10053/
  partyC: http://192.168.86.240:10056/
  regulator: http://192.168.86.240:10059/
  intervalPartyA: 300
  intervalPartyB: 75
  intervalPartyC: 120
  message: Heita Daarso! ons speel in Singapore, Broer!
  port: 10050
  config.rpc.host: localhost
  config.rpc.port: 10050
  config.rpc.username: user1
  config.rpc.password: test
